<x-layouts.app title="Terms and Conditions - BillRoll">
    <div class="pt-32 pb-20 lg:pt-40 lg:pb-28">
        <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 class="text-4xl font-bold text-gray-900 mb-8">Terms and Conditions</h1>
            
            <div class="prose prose-lg text-gray-600 max-w-none">
                <p class="mb-10 text-sm text-gray-500">Last updated: {{ date('F d, Y') }}</p>
                <p class="mb-10">Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the BillRoll mobile application (the "Service") operated by BillRoll ("us", "we", or "our").</p>
                
                <section class="mb-12">
                    <h2 class="text-2xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
                    <p>By downloading, installing, or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service. These Terms apply to all visitors, users, and others who access or use the Service.</p>
                </section>

                <section class="mb-12">
                    <h2 class="text-2xl font-bold text-gray-900 mb-4">2. License to Use</h2>
                    <p>We grant you a revocable, non-exclusive, non-transferable, limited license to download, install, and use the Application strictly in accordance with the terms of this Agreement.</p>
                </section>

                <section class="mb-12">
                    <h2 class="text-2xl font-bold text-gray-900 mb-4">3. Offline Data Storage & User Responsibility</h2>
                    <p class="mb-4">The Service operates as an offline-first application. You acknowledge and agree that:</p>
                    <ul class="list-disc pl-6 space-y-2">
                        <li><strong>Local Storage:</strong> All data generated by the Service (including invoices, client details, and settings) is stored locally on your device. We do not store, process, or have access to your data on any central server.</li>
                        <li><strong>Data Backups:</strong> You are solely responsible for maintaining backups of your data. We cannot recover lost data if you uninstall the app, clear your device storage, or lose your device.</li>
                        <li><strong>Data Security:</strong> While we implement standard local security measures, you are responsible for the physical security of your device to prevent unauthorized access to your billing data.</li>
                    </ul>
                </section>

                <section class="mb-12">
                    <h2 class="text-2xl font-bold text-gray-900 mb-4">4. Intellectual Property</h2>
                    <p>The Service and its original content (excluding content provided by you), features, and functionality are and will remain the exclusive property of BillRoll and its licensors. The Service is protected by copyright, trademark, and other laws.</p>
                </section>

                <section class="mb-12">
                    <h2 class="text-2xl font-bold text-gray-900 mb-4">5. Limitation of Liability</h2>
                    <p class="mb-4">In no event shall BillRoll, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:</p>
                    <ul class="list-disc pl-6 space-y-2 mb-4">
                        <li>Your access to or use of or inability to access or use the Service;</li>
                        <li>Any conduct or content of any third party on the Service;</li>
                        <li>Any content obtained from the Service; and</li>
                        <li>Unauthorized access, use or alteration of your transmissions or content.</li>
                    </ul>
                    <p>Since the App relies entirely on your device for storage, we are not liable for any data loss resulting from device failure, malware, or user error.</p>
                </section>

                <section class="mb-12">
                    <h2 class="text-2xl font-bold text-gray-900 mb-4">6. "As Is" and "As Available" Disclaimer</h2>
                    <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance.</p>
                </section>

                <section class="mb-12">
                    <h2 class="text-2xl font-bold text-gray-900 mb-4">7. Changes to Terms</h2>
                    <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.</p>
                </section>

                <section class="mb-12">
                    <h2 class="text-2xl font-bold text-gray-900 mb-4">8. Contact Us</h2>
                    <p>If you have any questions about these Terms, please contact us at terms@billroll.com.</p>
                </section>
            </div>
        </div>
    </div>
</x-layouts.app>
